# Development Docker Compose for GasLeap Team
# Full development environment with all services
version: '3.8'

services:
  # Local relay chain (for full XCM testing)
  relay-chain:
    image: parity/polkadot:latest
    ports:
      - "9942:9944"    # WebSocket RPC
      - "9932:9933"    # HTTP RPC
    volumes:
      - relay-data:/data
      - ./docker/relay-chain:/config
    environment:
      - RUST_LOG=info
    command: [
      "--chain=/config/relay-chain-spec.json",
      "--base-path=/data",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors=all",
      "--validator",
      "--alice",
      "--port=30333"
    ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9933/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - gasleap-network

  # GasLeap parachain node
  gasleap-node:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    ports:
      - "9944:9944"    # WebSocket RPC
      - "9933:9933"    # HTTP RPC
      - "30333:30333"  # P2P
    volumes:
      - gasleap-data:/data
      - ./docker/parachains:/config
    environment:
      - RUST_LOG=info
    command: [
      "--chain=/config/gasleap-parachain-spec.json",
      "--base-path=/data",
      "--ws-external",
      "--rpc-external", 
      "--rpc-cors=all",
      "--collator",
      "--alice",
      "--parachain-id=2000",
      "--relay-chain-rpc-url=ws://relay-chain:9944",
      "--port=30334"
    ]
    depends_on:
      relay-chain:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9933/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    networks:
      - gasleap-network

  # Astar local parachain
  astar-local:
    image: staketechnologies/astar-collator:latest
    ports:
      - "9945:9944"    # WebSocket RPC
      - "9934:9933"    # HTTP RPC
    volumes:
      - astar-data:/data
      - ./docker/parachains:/config
    environment:
      - RUST_LOG=info
    command: [
      "--chain=/config/astar-local-spec.json",
      "--base-path=/data",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors=all",
      "--collator",
      "--alice",
      "--parachain-id=2006",
      "--relay-chain-rpc-url=ws://relay-chain:9944",
      "--port=30335"
    ]
    depends_on:
      relay-chain:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9933/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    networks:
      - gasleap-network

  # Acala local parachain
  acala-local:
    image: acala/acala-node:latest
    ports:
      - "9946:9944"    # WebSocket RPC
      - "9935:9933"    # HTTP RPC
    volumes:
      - acala-data:/data
      - ./docker/parachains:/config
    environment:
      - RUST_LOG=info
    command: [
      "--chain=/config/acala-local-spec.json",
      "--base-path=/data",
      "--ws-external",
      "--rpc-external",
      "--rpc-cors=all",
      "--collator",
      "--alice",
      "--parachain-id=2034",
      "--relay-chain-rpc-url=ws://relay-chain:9944",
      "--port=30336"
    ]
    depends_on:
      relay-chain:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9933/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    networks:
      - gasleap-network

  # Demo data seeder
  demo-seeder:
    build:
      context: ./docker/scripts
      dockerfile: Dockerfile.seeder
    environment:
      - GASLEAP_ENDPOINT=ws://gasleap-node:9944
      - ASTAR_ENDPOINT=ws://astar-local:9944
      - ACALA_ENDPOINT=ws://acala-local:9944
    volumes:
      - demo-data:/data
    depends_on:
      gasleap-node:
        condition: service_healthy
      astar-local:
        condition: service_healthy
      acala-local:
        condition: service_healthy
    networks:
      - gasleap-network

  # Frontend development server
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_GASLEAP_ENDPOINT=ws://gasleap-node:9944
      - REACT_APP_ASTAR_ENDPOINT=ws://astar-local:9944
      - REACT_APP_ACALA_ENDPOINT=ws://acala-local:9944
      - REACT_APP_API_ENDPOINT=http://api-server:3003
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - gasleap-node
      - api-server
      - demo-seeder
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
      - gasleap-network

  # API Backend Service
  api-server:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
    container_name: gasleap-api-dev
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=postgresql://gasleap:gasleap123@postgres-db:5432/gasleap
      - REDIS_URL=redis://redis-cache:6379
      - NODE_ENV=development
      - GASLEAP_NODE_URL=ws://gasleap-node:9944
      - ASTAR_NODE_URL=ws://astar-local:9944
      - ACALA_NODE_URL=ws://acala-local:9944
    depends_on:
      - postgres-db
      - redis-cache
      - gasleap-node
    volumes:
      - ./backend/api:/app
      - /app/node_modules
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
      - gasleap-network

  # PostgreSQL Database
  postgres-db:
    image: postgres:15-alpine
    container_name: gasleap-postgres-dev
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gasleap
      - POSTGRES_USER=gasleap
      - POSTGRES_PASSWORD=gasleap123
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    networks:
      - gasleap-network

  # Redis Cache
  redis-cache:
    image: redis:7-alpine
    container_name: gasleap-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
    networks:
      - gasleap-network

  # Development Tools
  mailhog:
    image: mailhog/mailhog:latest
    container_name: gasleap-mailhog-dev
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'
    networks:
      - gasleap-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gasleap-pgadmin-dev
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gasleap.dev
      - PGADMIN_DEFAULT_PASSWORD=admin123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres-db
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    networks:
      - gasleap-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: gasleap-redis-commander-dev
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis-cache:6379
    depends_on:
      - redis-cache
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
    networks:
      - gasleap-network

  # Monitoring and Observability
  jaeger-tracing:
    image: jaegertracing/all-in-one:latest
    container_name: gasleap-jaeger-dev
    ports:
      - "16686:16686"  # Jaeger UI
      - "6831:6831/udp" # Jaeger agent
      - "14268:14268"   # Jaeger collector
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
    networks:
      - gasleap-network

  # NGINX Proxy for production-like setup
  nginx-proxy:
    image: nginx:alpine
    container_name: gasleap-nginx-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - frontend
      - api-server
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.1'
    networks:
      - gasleap-network

volumes:
  relay-data:
  gasleap-data:
  astar-data:
  acala-data:
  demo-data:
  postgres-data:
  redis-data:
  pgadmin-data:

networks:
  gasleap-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16